#ifndef SKYDOOM_SHARED_H
#define SKYDOOM_SHARED_H

#include "skydoom_protocol.h"

int SkyDoom_SharedInit(void);

void SkyDoom_SharedUpdate(void);

void SkyDoom_SharedShutdown(void);

void SkyDoom_OverlayCaptureBefore(void);

void SkyDoom_OverlayCaptureAfter(void);

void SkyDoom_OverlayCaptureStatusBar(void);

/*
    SKYDOOM_NATIVE_PICKUP_MESSAGES_V15_6

    Called immediately around Doom's own HU_Drawer().
    The before/after difference isolates the genuine Doom message
    glyphs without copying the hidden Doom world into Skyrim.
*/
void SkyDoom_OverlayCaptureHUDBefore(void);

void SkyDoom_OverlayCaptureHUDAfter(void);


/*
    Existing genuine Chocolate Doom pistol reporting.
*/

void SkyDoom_ReportPistolShotDamage(
    int damage
);


/*
    Normal-shotgun pellet reporting.

    angle_offset is the exact signed delta already generated by
    Chocolate Doom's P_SubRandom() spread calculation.
*/

void SkyDoom_ReportShotgunPellet(
    int damage,
    int32_t angle_offset,
    int32_t slope_offset
);





/*

    SKYDOOM_CHAINGUN_REPORT_V9



    One event per real Chocolate Doom chaingun bullet.

*/



void SkyDoom_ReportChaingunBullet(

    int damage,

    int32_t angle_offset,

    int32_t slope_offset

);







/*

    SKYDOOM_REAL_MELEE_V10



    Reports the real Chocolate Doom melee attack after its genuine

    damage and horizontal spread RNG have been consumed.

*/



void SkyDoom_ReportFistAttack(

    int damage,

    int32_t angle_offset

);



void SkyDoom_ReportChainsawAttack(

    int damage,

    int32_t angle_offset

);







/*

    SKYDOOM_REAL_ROCKET_V11



    A_FireMissile reports the genuine DOOM weapon fire.



    Skyrim owns projectile travel/collision because the hidden

    Chocolate Doom map is not Skyrim.



    On a Skyrim actor impact, Skyrim requests the genuine DOOM

    direct-hit P_Random roll from Chocolate Doom.

*/



int SkyDoom_SharedActive(void);

/* SKYDOOM_GUEST_NATIVE_PICKUP_ISOLATION_V15_9C1 */
int SkyDoom_GuestModeActive(void);

void SkyDoom_ReportRocketFired(void);
void SkyDoom_ReportPlasmaFired(void);
void SkyDoom_ReportBFGFired(void);
void SkyDoom_ReportBFGDamageRequest(
    int32_t request_id,
    int32_t spray
);

void SkyDoom_ReportPlasmaDamageRequest(
    int32_t request_id
);



void SkyDoom_ReportRocketDamageRequest(

    int32_t request_id

);



/*
    SKYDOOM_ARCADE: the DOOM minigame (-skydoomarcade).

    SkyDoom_ArcadeLevelDone: G_DoWorldDone calls this before loading the
    next level; returns 1 when the minigame stops there instead.
    SkyDoom_ArcadeEpisodeDone: the episode's ending text was shown.
*/
int SkyDoom_ArcadeLevelDone(int episode, int next_map);
void SkyDoom_ArcadeEpisodeDone(void);


#endif

